version: '2'
# Please use this with ./tasks run_local
services:
  default:
    links:
      - mq:mq
      - localstack:localstack
    ports:
      - 3000:3000
  mq:
    image: resilva87/docker-rabbitmq-stomp:3.0.0
  localstack:
    image: localstack/localstack
    ports:
      - "4572:4572"
      - "5555:5555"
    environment:
      - SERVICES=s3:4572
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=5555
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack/startup/create-bucket.sh:/docker-entrypoint-initaws.d/create-bucket.sh
      - "/var/run/docker.sock:/var/run/docker.sock"
