version: '2'
services:
  default:
    links:
      - gp2gp:gp2gp
      - mq-1:mq-1
      - mq-2:mq-2
      - localstack:localstack
  gp2gp:
    image: ${G2P_ADAPTOR_DOCKER_IMAGE}
    links:
      - mq-1:mq-1
      - mq-2:mq-2
      - localstack:localstack
  mq-1:
    image: resilva87/docker-rabbitmq-stomp:3.0.0
  mq-2:
    image: resilva87/docker-rabbitmq-stomp:3.0.0
  localstack:
    image: localstack/localstack
    ports:
      - "4572:4572"
      - "5555:5555"
    environment:
      - SERVICES=s3:4572
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=5555
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack/startup/create-bucket.sh:/docker-entrypoint-initaws.d/create-bucket.sh
      - "/var/run/docker.sock:/var/run/docker.sock"
