version: '2'
services:
  default:
    links:
      - gp2gp:gp2gp
      - mq-1:mq-1
      - mq-2:mq-2
      - mq-3:mq-3
  gp2gp:
    image: ${G2P_ADAPTOR_DOCKER_IMAGE}
    links:
      - mq-1:mq-1
      - mq-2:mq-2
      - mq-3:mq-3
  mq-1:
    image: resilva87/docker-rabbitmq-stomp:3.0.0
  mq-2:
    image: resilva87/docker-rabbitmq-stomp:3.0.0
  mq-3:
    image: rabbitmq:3.8.2